import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import EducationalBanner from "@/components/EducationalBanner";
import Footer from "@/components/Footer";
import MobileNav from "@/components/MobileNav";
import { getCompanies, getLatest } from "@/lib/data";

import { WatchlistProvider } from "@/context/WatchlistContext";
import AIChatbot from "@/components/AIChatbot";

export const metadata: Metadata = {
  title: "ForecastPH | Educational Stock Forecasting",
  description: "Educational PSE stock price forecasts generated by an automated ML pipeline.",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const [companies, latest] = await Promise.all([getCompanies(), getLatest()]);

  return (
    <html lang="en" className="dark scroll-smooth" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                var theme = localStorage.getItem('theme');
                if (theme === 'light') {
                  document.documentElement.classList.remove('dark');
                } else {
                  document.documentElement.classList.add('dark');
                }
              } catch (_) {}
            `,
          }}
        />
      </head>
      <body className="bg-slate-50 dark:bg-charcoal-950 text-slate-900 dark:text-slate-100 font-sans antialiased overflow-x-hidden min-h-screen flex flex-col">
        <WatchlistProvider validSymbols={companies.map((company) => company.symbol)}>
          <Navbar companies={companies} />
          <EducationalBanner latest={latest} />
          <main className="flex-grow max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 mb-20 md:mb-8">
            {children}
          </main>
          <AIChatbot />
          <MobileNav />
          <Footer />
        </WatchlistProvider>
      </body>
    </html>
  );
}
