import { formatDateTime } from "@/lib/format";
import type { LatestData } from "@/lib/types";

export default function EducationalBanner({ latest }: { latest: LatestData | null }) {
  return (
    <div className="bg-charcoal-900/80 backdrop-blur-md border-b border-charcoal-700/80 text-center py-2 px-4 text-xs text-slate-300 mt-16 relative z-40">
      <strong className="text-neon-400 font-semibold">Educational Purpose Only:</strong> Forecasts are generated by an automated
      machine-learning pipeline from historical PSE data and should not be used as financial advice.
      {latest?.lastRunAt && (
        <span className="block sm:inline sm:ml-2 text-slate-400 font-mono text-[11px]">
          Data last refreshed: {formatDateTime(latest.lastRunAt)} (status: <span className="text-accent-emerald font-semibold">{latest.status}</span>)
        </span>
      )}
    </div>
  );
}
